### ISSUE TITLE
README outline section contains weird text

### ISSUE THREAD

**Issue by gsauthof** [PacktPublishing/Linux-Kernel-Programming_2E#1]
Currently, the README contains the following text:

https://github.com/PacktPublishing/Linux-Kernel-Programming_2E/blob/377b7a3290ae389fdec5a7d7fcef3c19cd7a012e/README.md?plain=1#L27

cf, https://github.com/PacktPublishing/Linux-Kernel-Programming_2E/blame/377b7a3290ae389fdec5a7d7fcef3c19cd7a012e/README.md#L27

Looks like it's a copy'n'paste error from another book, e.g. from:

> This book covers everything from setting up ASP.NET Core 8 and modern Angular to deploying robust web applications in Windows, Linux, and Azure. Learn advanced techniques in data handling, API usage, UI design, and security

https://github.com/PacktPublishing/ASP.NET-Core-8-and-Angular/blob/fcee019e383649da722d2a3eb2ed1f41f0517cd3/README.md?plain=1#L30

(NB: This sentence there could probably also benefit from a full stop.)

**Comment by kaiwan** [comment]
Done, fixed. Thank you @gsauthof for raising this.
Commit # ac37b21
