### ISSUE TITLE
Need to disable module compress 

### ISSUE THREAD

**Issue by redbilledpanda** [PacktPublishing/Linux-Kernel-Programming_2E#2]
Hello Kaiwan. Great book! 

Just found a minor inconsistency which I'd like to bring to your attention.

Just realized modern kernels (> [5.13 apparently](https://www.phoronix.com/news/Linux-5.13-Zstd-Modules)) for x86_64 enable module compression by default which is why when we install modules, the compressed version of it gets installed. On the stock version of 6.1.25, compression mode was set to ZSTD in my own case. The book however expects us to find ***.ko** files at _/lib/modules/$(kernel-name)/kernel_.

It would be great if you could update the errata/addendum list to indicate that we need to set module compression to None at:
_Enable loadable module support -->Module compression mode (None)_

That is all!

**Comment by kaiwan** [comment]
@redbilledpanda thanks v much! Have added this to the Known Errata section
