### ISSUE TITLE
cgroupsv2_explore doesn't show memory information and footnote when CPU controller is disabled

### ISSUE THREAD

**Issue by eibisidi** [PacktPublishing/Linux-Kernel-Programming_2E#4]
Running ch11/cgroups/cgroupsv2_explore  doesn't show memory information and footnote, 
When  CPU controller is disabled && memory controller is enabled.

![image](https://github.com/user-attachments/assets/9d6cc865-d0c6-4a61-9d29-dfc151862228)

`#  $1 : path to cg`
`cpu_ctrl_show()`
`{`
`  [...]`
`  [[ ! -z "${cpu_pressure}" ]] &&    printf "      %-39s   : %s\n" "cpu.pressure" "${cpu_pressure}"`
` fi`
`# !!!!!!!!!!!return 0   !!!!!!!!!!! is needed here, because of previous set -e.`
`}`

`  core_cg_files_show ${cg}`
`  cpu_ctrl_show ${cg}         #!!!!!!!!!!!!!aborts here`
`  mem_ctrl_show ${cg}      #!!!!!!!!!!!!!wont' be called`

**Comment by kaiwan** [comment]
Okay, thanks.. A bit busy now, I'll look into it soon

**Comment by eibisidi** [comment]
Issue fixed in Commit 2662dd1.
[https://github.com/PacktPublishing/Linux-Kernel-Programming_2E/commit/2662dd18f82a836a9c1bbb39fbe7ca63b3825fc1](url)
