### ISSUE TITLE
Can't compile ch5/min_sysinfo

### ISSUE THREAD

**Issue by wiktorjl** [PacktPublishing/Linux-Kernel-Programming_2E#6]
Pulled the latest code and run "make", receive the errors below. What fixes it is adding function prototypes on top.
```


--- Building : KDIR=/lib/modules/6.10.10-lkp-dbg/build ARCH= CROSS_COMPILE= ccflags-y="-UDEBUG -DDYNAMIC_DEBUG_MODULE" MYDEBUG=n DBG_STRIP=n ---
gcc (Debian 12.2.0-14) 12.2.0

make -C /lib/modules/6.10.10-lkp-dbg/build M=/home/user/data/Linux-Kernel-Programming_2E/ch5/min_sysinfo modules
make[1]: Entering directory '/home/user/data/kernels/linux-6.10.10'
  CC [M]  /home/user/data/Linux-Kernel-Programming_2E/ch5/min_sysinfo/min_sysinfo.o
/home/user/data/Linux-Kernel-Programming_2E/ch5/min_sysinfo/min_sysinfo.c:40:5: error: no previous prototype for ‘my_snprintf_lkp’ [-Werror=missing-prototypes]
   40 | int my_snprintf_lkp(char *buf, size_t maxsize, const char *fmt, ...)
      |     ^~~~~~~~~~~~~~~
/home/user/data/Linux-Kernel-Programming_2E/ch5/min_sysinfo/min_sysinfo.c:68:6: error: no previous prototype for ‘show_sizeof’ [-Werror=missing-prototypes]
   68 | void show_sizeof(void)
      |      ^~~~~~~~~~~
/home/user/data/Linux-Kernel-Programming_2E/ch5/min_sysinfo/min_sysinfo.c:84:6: error: no previous prototype for ‘llkd_sysinfo2’ [-Werror=missing-prototypes]
   84 | void llkd_sysinfo2(void)
      |      ^~~~~~~~~~~~~
/home/user/data/Linux-Kernel-Programming_2E/ch5/min_sysinfo/min_sysinfo.c:157:6: error: no previous prototype for ‘llkd_sysinfo’ [-Werror=missing-prototypes]
  157 | void llkd_sysinfo(void)
      |      ^~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:244: /home/user/data/Linux-Kernel-Programming_2E/ch5/min_sysinfo/min_sysinfo.o] Error 1
make[2]: *** [/home/user/data/kernels/linux-6.10.10/Makefile:1934: /home/user/data/Linux-Kernel-Programming_2E/ch5/min_sysinfo] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/home/user/data/kernels/linux-6.10.10'
make: *** [Makefile:131: all] Error 2

```

**Comment by kaiwan** [comment]
Thanks for your report!
Are you compiling with -Werror i.e. treat warnings as errors?  ..as that's what's happening here:
`cc1: all warnings being treated as errors`

In any case, it's as these functions (deliberately) aren't marked as static so that we can export and use them in other modules... to fix the warning/error, i'll declare the prototypes; pl pull again and retry, thanks.

**Comment by wiktorjl** [comment]
Thanks. I used both the lkm script and make by itself - without any local modifications. I can confirm min_sysinfo now compiles, but the same issue exists in modstacking.

**Comment by kaiwan** [comment]
Ok.. can you provide your platform details pl: distro version, gcc version, anything else that may be relevant.. thanks

**Comment by wiktorjl** [comment]
I have a plain vanilla debian 12 installation with kernel updated to 6.10.10:

OS: Debian GNU/Linux 12 (bookworm) x86_64
gcc: gcc (Debian 12.2.0-14) 12.2.0
kernel: 6.10.10
make: GNU Make 4.3

**Comment by kaiwan** [comment]
I find that these remain compiler warnings on my platforms (i even tried on a very recent 6.11 kernel on x86 Ubuntu), of the form:
`core_lkm.c:43:6: warning: no previous prototype for ‘llkd_sysinfo2’ [-Wmissing-prototypes]`
It doesn't throw an error as you seem to be getting; am unsure why this is... (perhaps Debian forces the -Werror?).
In any case, I've declared the func prototypes & added a commit - with credit to you.. Thank you
