### ISSUE TITLE
ch7/show_kernel_vas compile time error

### ISSUE THREAD

**Issue by eibisidi** [PacktPublishing/Linux-Kernel-Programming_2E#7]
Hi!
I found that on my environment, ch7/show_kernel_vas won't compile.
gcc complains:
![image](https://github.com/user-attachments/assets/f57c9fab-a488-4fad-b217-ccbbdce4a726)
It seems to be  the outmost () of SHOW_DELTA_x macros which causes the compile error.
Comma expression inside ((low), (high), ((high)-(low))) evalutes to the last expression ((high)-(low)).
As a result, pr_info(format, SHOW_DELTA_x()) leads to  specifiers number and arguments number mismatch.

Removing the outmost () will do:
diff --git a/convenient.h b/convenient.h
index 4603733..4443851 100644
--- a/convenient.h
+++ b/convenient.h
@@ -123,15 +123,15 @@
  * as required.
  * Inspired from raspberry pi kernel src: arch/arm/mm/init.c:MLM()
  */
-#define SHOW_DELTA_b(low, hi) ((low), (hi), ((hi) - (low)))
-#define SHOW_DELTA_K(low, hi) ((low), (hi), (((hi) - (low)) >> 10))
-#define SHOW_DELTA_M(low, hi) ((low), (hi), (((hi) - (low)) >> 20))
-#define SHOW_DELTA_G(low, hi) ((low), (hi), (((hi) - (low)) >> 30))
-#define SHOW_DELTA_MG(low, hi) ((low), (hi), (((hi) - (low)) >> 20), (((hi) - (low)) >> 30))
+#define SHOW_DELTA_b(low, hi) (low), (hi), ((hi) - (low))
+#define SHOW_DELTA_K(low, hi) (low), (hi), (((hi) - (low)) >> 10)
+#define SHOW_DELTA_M(low, hi) (low), (hi), (((hi) - (low)) >> 20)
+#define SHOW_DELTA_G(low, hi) (low), (hi), (((hi) - (low)) >> 30)
+#define SHOW_DELTA_MG(low, hi) (low), (hi), (((hi) - (low)) >> 20), (((hi) - (low)) >> 30)
 #if (BITS_PER_LONG == 64)
-#define SHOW_DELTA_MGT(low, hi) ((low), (hi), (((hi) - (low)) >> 20), (((hi) - (low)) >> 30), (((hi) - (low)) >> 40))
+#define SHOW_DELTA_MGT(low, hi) (low), (hi), (((hi) - (low)) >> 20), (((hi) - (low)) >> 30), (((hi) - (low)) >> 40)
 #else // 32-bit
-#define SHOW_DELTA_MGT(low, hi) ((low), (hi), (((hi) - (low)) >> 20), (((hi) - (low)) >> 30))
+#define SHOW_DELTA_MGT(low, hi) (low), (hi), (((hi) - (low)) >> 20), (((hi) - (low)) >> 30)
 #endif
 
 #ifdef __KERNEL__

**Comment by kaiwan** [comment]
Have applied your fix, thanks! Included 'Reported-by: eibisidi' in the commit
